name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  linux:
    name: Build linux binaries
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: registry.hub.docker.com/library/debian:bookworm-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install nightly rust
        run: |
          apt-get update -y
          apt-get install -y --no-install-recommends curl clang lld ca-certificates
          update-ca-certificates
          curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly-2023-02-22 --profile minimal -y
          . $HOME/.cargo/env
          rustup component add rust-src
          rustup target add x86_64-unknown-linux-musl
          rustup target add i686-unknown-linux-musl
          rustup target add aarch64-unknown-linux-musl
      - name: Build
        run: |
          . $HOME/.cargo/env
          mkdir dist
          for ARCH in x86_64 i686 aarch64; do
            cargo build --release --target $ARCH-unknown-linux-musl -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
            cp target/$ARCH-unknown-linux-musl/release/focused_prompt dist/focused_prompt-$ARCH-linux
          done
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/*
